#python3 metric_test_exec_ensemble.py  --expe_name="REAL_256" --subsample 16 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> outREAL.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="INVERSION_200" --subsample 16 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &> out_inv_1000.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test1.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test2.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test3.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test4.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test5.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test6.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test7.txt &

#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test7.txt &

#python3 metric_test_exec_ensemble.py  --expe_name="REAL_256_TEST" --debiasing=False --subsample 16 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/'

#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test1.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test2.txt &

#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test3.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test3.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0']"  --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']"  --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '0', '1', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '1', '1', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '0', '1', '1', '1', '1', '0', '0', '1', '1', '1', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '0', '1', '0', '1', '0', '0', '1', '1',''1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '0', '1', '1', '0', '1', '1', '1', '1', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '0', '0', '1', '1', '1', '1', '1', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '1', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '1', '1', '1', '0', '0', '0', '0', '0', '1', '0', '1', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'



#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']_reduced" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="REAL_256" --subsample 16 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/'
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="extrapolation_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 240 --conditioning_members=16 --inv_step=1000 --N_ensemble=240 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=800 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=800 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=800 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=800 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="extrapolation_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 240 --conditioning_members=16 --inv_step=800 --N_ensemble=240 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=600 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=600 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=600 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=600 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="extrapolation_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 240 --conditioning_members=16 --inv_step=600 --N_ensemble=240 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 112 --conditioning_members=16 --inv_step=400 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=400 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=400 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=400 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="extrapolation_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 240 --conditioning_members=16 --inv_step=400 --N_ensemble=240 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=200 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=200 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=200 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=200 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="extrapolation_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 240 --conditioning_members=16 --inv_step=200 --N_ensemble=240 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &


#### AVANT INVSTEPS APRES COND_members

#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="extrapolation_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 240 --conditioning_members=16 --inv_step=1000 --N_ensemble=240 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=8 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=8 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=8 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=8 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="extrapolation_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 56 --conditioning_members=8 --inv_step=1000 --N_ensemble=56 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=4 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=4 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=4 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=4 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="extrapolation_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 12 --conditioning_members=4 --inv_step=1000 --N_ensemble=12 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=2 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=2 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=2 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=2 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="extrapolation_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='ENSAVG' --subsample 2 --conditioning_members=2 --inv_step=1000 --N_ensemble=2 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=1 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=1 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '0', '0', '1', '0', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=1 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '1', '0', '1', '1', '0', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=1 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '0', '0', '0', '0', '0', '1', '1', '1', '1', '1', '1']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '0', '0', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing='SEED' --subsample 112 --conditioning_members=16 --inv_step=1000 --N_ensemble=112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/mrmn/brochetc/GAN_2D/datasets_full_indexing/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/mrmn/moldovang/obs_databases/obs_full_npy/' &
