#python3 metric_test_exec_ensemble.py  --expe_name="REAL_TEST" --subsample 16 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> outREAL.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="INV_200_TEST" --subsample 16 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_inv_800.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test1.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test2.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test3.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test4.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test5.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test6.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test7.txt &

#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test7.txt &

#python3 metric_test_exec_ensemble.py  --expe_name="REAL_256_TEST" --debiasing=False --subsample 16 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/'

#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test1.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="random_['1', '0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test2.txt &

#python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test3.txt &
#python3 metric_test_exec_ensemble.py  --expe_name="normal_['0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --debiasing=True --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/' &> out_test3.txt &
python3 metric_test_exec_ensemble.py  --expe_name="normal_['1', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0']"  --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/'
python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']"  --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/'
python3 metric_test_exec_ensemble.py  --expe_name="random_['0', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']" --subsample 112 --num_proc 8 --variables=['u','v','t2m'] --data_dir_real='/scratch/work/brochetc/datasets/IS_1_1.0_0_0_0_0_0_256_large_lt_done/' --data_dir_obs='/scratch/work/brochetc/datasets/obs_full_npy/'


